# # Play Word
# ctrl+shift+z:
#   x: 1700
#   y: 537
# # Play Sentence
# ctrl+shift+x:
#   x: 1502
#   y: 503
# # Start / End
# ctrl+shift+space:
#   x: 1696
#   y: 968
# # Next
# ctrl+shift+a:
#   x: 1843
#   y: 962

# temp
ctrl+shift+1: # <--
  x: 646
  y: 733
ctrl+shift+2: # -->
  x: 746
  y: 743
ctrl+shift+3: # select
  x: 915
  y: 678
ctrl+shift+4: # save
  x: 1149
  y: 739